// <auto-generated />
using System;
using CartDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CartDb.Migrations
{
    [DbContext(typeof(CartContext))]
    [Migration("20200726111747_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CartDb.Entities.CartSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<DateTime>("ExpiresDateTime");

                    b.HasKey("Id");

                    b.ToTable("CartSessions");
                });

            modelBuilder.Entity("CartDb.Entities.CartSessionDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CartSessionId");

                    b.Property<float>("Price");

                    b.Property<Guid>("ProductId");

                    b.Property<string>("ProductName");

                    b.HasKey("Id");

                    b.HasIndex("CartSessionId");

                    b.ToTable("CartSessionDetails");
                });

            modelBuilder.Entity("CartDb.Entities.CartSessionDetail", b =>
                {
                    b.HasOne("CartDb.Entities.CartSession", "CartSession")
                        .WithMany("SessionOrderLines")
                        .HasForeignKey("CartSessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
